VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Form_Menu"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub btnCompletedRequests_Click()
    DoCmd.OpenForm "frmParametersforCompleted"
End Sub

Private Sub btnImportDataFromSystem_Click()
    DoCmd.OpenForm "FrmInsertUpdates"
End Sub

Private Sub btnInsertNewBarcode_Click()
    DoCmd.OpenForm "DlgInsertNewBarCode"
End Sub

Private Sub btnRegisterReturnedRequests_Click()
    DoCmd.OpenForm "FrmInsertReturnedBarcodes"
End Sub

Private Sub Form_Load()
    DoCmd.Maximize
End Sub
